### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by Xfolchf** [decidim/decidim-module-mentions#1]
It should be possible to mention a user in the comments so that he/she receives a direct message notifying them that they have been mentioned.

**Comment by isaacmg410** [comment]
Is necessary to add a unique nickname for each user. 
A migration must be created to create the users nicknames. (via the name, if the nickname already exists, numbers are added at the end)

For a MVP, the user can't change the nickname. @decidim/product is it ok? Need to discus what happens if user can change their nickname and is mentioned to the comments. 
For a MVP, can't mention a user_group.

**Comment by xabier** [comment]
good for MVP, please @isaacmg410 create the issues that are necessary for @decidim/lot-core 

It is very probable that users might want to change their nickname as soon as they discover this feature, we need to anticipate what happens in that case, particularly because many people might have chosen long names.

**Comment by arnaumonty** [comment]
@isaacmg410 the unique nickname has been developed and closed in the issue #2335. 

> For a MVP, the user can't change the nickname. @decidim/product is it ok? Need to discuss what happens if user can change their nickname and is mentioned in the comments.
The behaviour should be to replace the old nickname with the new one in case the user changes its own nickname.

**Comment by oriolgual** [comment]
Maybe I got it wrong, but why is this a new module instead of an improvement on core? It's hard for me to image doing this without modifying the core.

**Comment by isaacmg410** [comment]
Why don't put it inside the comment module? As the issue says, it is used when the user is mentioned in the comments...

**Comment by arnaumonty** [comment]
It should work in comments but also on proposals, debates, projects,...this is why it should be done it on core as @oriolgual said. We should find the way to work it together. Maybe we can discuss it next monday.

**Comment by mrcasals** [comment]
@arnaumonty @isaacmg410 my idea on this was to create a series of "content parsers", each of them would receive a body of something and return it modified. They could be saved into an array on an initializer (think of it as the same system as abilities are registered). Then, when the content is submitted, we pass the content through the parsers.

Each parser modifies the content yb doing a single thing. For example:

- Mention parser: searches the content for `@foobar`, looks for users with `foobar` as username and links the work to the user profile if it exists. 
- Reference parser: looks for words matching a resource reference and links the reference to the corresponding resource. Think of it as what GitHub does when you write `#123`, where `123` is the ID of an issue/PR.

New components and apps could extend these parsers and add their own if they need to.

In order to do this, you'd need to:

1. Modify `core` to create the array of parsers and add a class to wrap these parsers so the API is the same for everyone
1. Add the mentions parser to `core`
2. Modify `comments` to parse the comments body before saving

There's no need to create a whole module for this.

**Comment by arnaumonty** [comment]
Then we should move this issue to [decidim repo](https://github.com/decidim/decidim) and close this repo.
cc @josepjaume @andreslucena

**Comment by mrcasals** [comment]
Another parser idea would be a hashtag parser, in order to find `#foobar` and link to the hashtag page

**Comment by xabier** [comment]
@mrcasals you idea of parsers makes a lot of sense! I really like it! It also matches the needs of the hashtag component Also I agree with moving this discussion to core and decidim/decidim repository
